import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const STORAGE_KEY = 'nyaysaathi_lang'

const STRINGS = {
  en: {
    common: {
      home: 'Home',
      categories: 'Categories',
      loading: 'Loading…',
      tryAgain: 'Try Again',
    },
    nav: {
      home: 'Home',
      find: 'Find Guidance',
      browse: 'Browse',
      signin: 'Sign In',
      getHelp: 'Get Help →',
      getHelpNow: 'Get Help Now',
      language: 'Language',
      legalGuidance: 'Legal Procedural Guidance',
    },
    home: {
      forCitizens: '🇮🇳 For Every Indian Citizen',
      title1: "Don't Know Your",
      title2: 'Legal Rights?',
      title3: "We'll Guide You.",
      subtitle: 'Describe your problem in simple words. NyaySaathi tells you exactly what steps to take, which authority to approach, and what documents you need — in plain language.',
      noteTitle: '⚠️ Important Note',
      noteBody: 'NyaySaathi provides procedural guidance only — not legal advice. For legal representation, consult a qualified advocate.',
      legalAid: 'Free legal aid: Call',
      howItWorks: 'How NyaySaathi Works',
      howSub: 'Three simple steps to get procedural guidance',
      browseTitle: 'Browse by Category',
      browseSub: '10 categories covering the most common legal problems faced by Indian citizens',
      ctaTitle: 'Facing a Legal Problem Right Now?',
      ctaSub: "Get free procedural guidance instantly — no registration required.",
      ctaBtn: "Get Help Now — It's Free →",
      stats: {
        workflows: 'Legal Workflows',
        categories: 'Categories',
        free: 'Always Free',
        available: 'Available',
      },
      steps: {
        oneTitle: 'Describe Your Problem',
        oneDesc: 'Type your problem in plain language — no legal jargon needed.',
        twoTitle: 'We Find the Match',
        twoDesc: 'AI search matches your problem to the right legal workflow from 201 cases.',
        threeTitle: 'Follow the Steps',
        threeDesc: 'Get step-by-step guidance, required documents, and helpline numbers.',
      },
    },
    search: {
      badge: '⚖️ Free Legal Procedural Guidance',
      title: 'Describe Your Legal Problem',
      subtitle: 'Write in simple language — Hindi words, broken English, anything. Our system understands your problem and finds the right guidance.',
      commonTitle: 'Common problems people ask about:',
      disclaimer: '⚠️ Disclaimer: NyaySaathi provides procedural guidance only. This is NOT legal advice. For free legal aid, call',
    },
    searchBox: {
      placeholder: 'Describe your legal problem in your own words…',
      button: 'Find Guidance →',
      tryAsking: 'Try asking:',
      examples: [
        'My employer has not paid salary for 2 months',
        'Someone scammed me through UPI payment',
        'My neighbour is encroaching on my land',
        'Landlord is not returning my security deposit',
        'I received a defective product from online shopping',
      ],
    },
    results: {
      analysing: 'Analysing your problem…',
      understoodAs: 'System understood your query as:',
      aiEnhanced: '⚡ AI Enhanced',
      high: 'High confidence',
      medium: 'Medium confidence',
      low: 'Low confidence',
      matchesFound: 'matching guidance workflows found',
      oneMatchFound: 'matching guidance workflow found',
      noResults: 'No results found',
      disclaimer: '⚠️ Disclaimer: NyaySaathi provides procedural guidance only — not legal advice. For free legal aid, call',
      browseAll: 'Browse all categories →',
    },
    categories: {
      title: '📚 Browse Legal Categories',
      subtitle: '✨ Explore all 10 problem categories and 201 legal workflows',
      allCategories: '🗂️ All Categories',
      workflows: 'workflows',
      selectPromptTitle: '👆 Select a category to browse',
      selectPromptBody: 'Choose any category from the list to see all related legal workflows.',
      searchDirect: '🔎 Or search your problem directly →',
      loadingCats: 'Loading categories…',
      loadingCases: 'Loading cases…',
      viewGuidance: '👉 View Guidance →',
    },
    caseCard: {
      stepsToFollow: 'steps to follow',
      moreSteps: 'more steps',
      documentsNeeded: 'documents needed',
      viewFull: 'View Full Guidance →',
      match: 'match',
    },
    caseDetail: {
      loading: 'Loading guidance…',
      couldNotCopy: 'Could not copy. Please select and copy the text manually.',
      stepsTitle: '📋 Steps to Follow',
      escalationTitle: '⬆️ Escalation Path',
      templateTitle: '📝 Complaint Template',
      copied: '✅ Copied!',
      copy: '📋 Copy',
      requiredDocs: '📄 Required Documents',
      whomToApproach: '🏛️ Whom to Approach',
      level: 'level',
      portals: '🌐 Online Portals',
      helplines: '📞 Helpline Numbers',
      legalHelp: '🆓 Need Free Legal Help?',
      legalHelpBody: 'District Legal Services Authority (DLSA) provides free legal aid to eligible citizens.',
      callFree: '📞 Call 15100 (Free)',
      disclaimer: '⚠️ Disclaimer: This is procedural guidance only, not legal advice. Always consult a qualified advocate for your specific situation.',
    },
    signin: {
      title: '🔐 Sign In',
      subtitle: 'Log in to your NyaySaathi account.',
      email: 'Email',
      password: 'Password',
      button: 'Sign In',
      demoNote: 'This is a demo sign-in (no real authentication).',
      success: '✅ Signed in successfully (demo).',
    },
    feedback: {
      searching: 'Searching for guidance…',
      searchingSub: 'Searching across 201 legal workflows',
      wentWrong: 'Something went wrong',
      unexpected: 'An unexpected error occurred. Please try again.',
      noMatching: 'No matching cases found',
      noMatchingMsgA: "We couldn't find a match for",
      noMatchingMsgB: 'Try describing your problem in different words.',
      tips: 'Tips:',
      tip1: 'Use simple words (e.g. "landlord not returning deposit")',
      tip2: 'Mention the type of problem (land, salary, cyber fraud…)',
      tip3: 'Try the Browse Categories page to explore manually',
    },
    footer: {
      legalDisclaimer: 'Legal Disclaimer:',
      legalBody: 'NyaySaathi provides procedural guidance only and does NOT constitute legal advice. For legal advice, consult a qualified advocate. Free legal aid is available at your nearest District Legal Services Authority (DLSA) — call',
      tagline: 'Empowering ordinary citizens with legal procedural knowledge. Free. Simple. Accessible.',
      navigate: 'Navigate',
      browseCategories: 'Browse Categories',
      emergency: 'Emergency Helplines',
      builtFor: 'Built for the people of India.',
      workflowsAndCats: '201 legal workflows · 10 categories',
    },
  },
  hi: {
    common: {
      home: 'होम',
      categories: 'श्रेणियां',
      loading: 'लोड हो रहा है…',
      tryAgain: 'फिर कोशिश करें',
    },
    nav: {
      home: 'होम',
      find: 'मार्गदर्शन खोजें',
      browse: 'ब्राउज़',
      signin: 'साइन इन',
      getHelp: 'मदद लें →',
      getHelpNow: 'अभी मदद लें',
      language: 'भाषा',
      legalGuidance: 'कानूनी प्रक्रिया मार्गदर्शन',
    },
    home: {
      forCitizens: '🇮🇳 हर भारतीय नागरिक के लिए',
      title1: 'अपने',
      title2: 'कानूनी अधिकार',
      title3: 'नहीं पता? हम मार्गदर्शन करेंगे।',
      subtitle: 'अपनी समस्या सरल शब्दों में लिखें। NyaySaathi बताएगा कि कौन से कदम उठाने हैं, किस प्राधिकरण से संपर्क करना है और कौन से दस्तावेज चाहिए।',
      noteTitle: '⚠️ महत्वपूर्ण सूचना',
      noteBody: 'NyaySaathi केवल प्रक्रिया संबंधी मार्गदर्शन देता है, कानूनी सलाह नहीं। कानूनी प्रतिनिधित्व के लिए योग्य वकील से सलाह लें।',
      legalAid: 'मुफ़्त कानूनी सहायता: कॉल करें',
      howItWorks: 'NyaySaathi कैसे काम करता है',
      howSub: 'प्रक्रियात्मक मार्गदर्शन पाने के 3 सरल कदम',
      browseTitle: 'श्रेणी अनुसार देखें',
      browseSub: 'भारतीय नागरिकों की सामान्य कानूनी समस्याओं की 10 श्रेणियां',
      ctaTitle: 'अभी कानूनी समस्या का सामना कर रहे हैं?',
      ctaSub: 'तुरंत मुफ़्त प्रक्रिया मार्गदर्शन पाएं — बिना पंजीकरण।',
      ctaBtn: 'अभी मदद लें — यह मुफ़्त है →',
      stats: {
        workflows: 'कानूनी वर्कफ़्लो',
        categories: 'श्रेणियां',
        free: 'हमेशा मुफ़्त',
        available: 'उपलब्ध',
      },
      steps: {
        oneTitle: 'अपनी समस्या बताएं',
        oneDesc: 'सरल भाषा में लिखें — कानूनी शब्दों की जरूरत नहीं।',
        twoTitle: 'हम सही मैच खोजते हैं',
        twoDesc: 'AI आपकी समस्या को 201 केसों में सही कानूनी वर्कफ़्लो से मिलाता है।',
        threeTitle: 'कदमों का पालन करें',
        threeDesc: 'स्टेप-बाय-स्टेप मार्गदर्शन, दस्तावेज और हेल्पलाइन पाएं।',
      },
    },
    search: {
      badge: '⚖️ मुफ्त कानूनी प्रक्रिया मार्गदर्शन',
      title: 'अपनी कानूनी समस्या बताएं',
      subtitle: 'सरल भाषा में लिखें — हिंदी, टूटी-फूटी अंग्रेज़ी, कुछ भी। सिस्टम आपकी समस्या समझकर सही मार्गदर्शन ढूंढेगा।',
      commonTitle: 'लोग अक्सर यह समस्याएं पूछते हैं:',
      disclaimer: '⚠️ अस्वीकरण: NyaySaathi केवल प्रक्रिया मार्गदर्शन देता है। यह कानूनी सलाह नहीं है। मुफ़्त कानूनी सहायता के लिए कॉल करें',
    },
    searchBox: {
      placeholder: 'अपनी कानूनी समस्या अपने शब्दों में लिखें…',
      button: 'मार्गदर्शन खोजें →',
      tryAsking: 'ऐसे पूछकर देखें:',
      examples: [
        'मेरे नियोक्ता ने 2 महीने से वेतन नहीं दिया',
        'UPI पेमेंट से मेरे साथ धोखाधड़ी हुई',
        'पड़ोसी मेरी जमीन पर कब्जा कर रहा है',
        'मकान मालिक सुरक्षा जमा वापस नहीं कर रहा',
        'ऑनलाइन खरीदा सामान खराब निकला',
      ],
    },
    results: {
      analysing: 'आपकी समस्या का विश्लेषण हो रहा है…',
      understoodAs: 'सिस्टम ने आपकी क्वेरी ऐसे समझी:',
      aiEnhanced: '⚡ AI उन्नत',
      high: 'उच्च भरोसा',
      medium: 'मध्यम भरोसा',
      low: 'कम भरोसा',
      matchesFound: 'मिलते-जुलते मार्गदर्शन वर्कफ़्लो मिले',
      oneMatchFound: 'मिलता-जुलता मार्गदर्शन वर्कफ़्लो मिला',
      noResults: 'कोई परिणाम नहीं मिला',
      disclaimer: '⚠️ अस्वीकरण: NyaySaathi केवल प्रक्रिया मार्गदर्शन देता है, कानूनी सलाह नहीं। मुफ़्त कानूनी सहायता के लिए कॉल करें',
      browseAll: 'सभी श्रेणियां देखें →',
    },
    categories: {
      title: '📚 कानूनी श्रेणियाँ ब्राउज़ करें',
      subtitle: '✨ 10 श्रेणियाँ और 201 कानूनी वर्कफ़्लो देखें',
      allCategories: '🗂️ सभी श्रेणियाँ',
      workflows: 'वर्कफ़्लो',
      selectPromptTitle: '👆 ब्राउज़ करने के लिए श्रेणी चुनें',
      selectPromptBody: 'सूची से कोई भी श्रेणी चुनें और संबंधित कानूनी वर्कफ़्लो देखें।',
      searchDirect: '🔎 या अपना सवाल सीधे खोजें →',
      loadingCats: 'श्रेणियाँ लोड हो रही हैं…',
      loadingCases: 'वर्कफ़्लो लोड हो रहे हैं…',
      viewGuidance: '👉 मार्गदर्शन देखें →',
    },
    caseCard: {
      stepsToFollow: 'फॉलो करने के कदम',
      moreSteps: 'और कदम',
      documentsNeeded: 'दस्तावेज़ आवश्यक',
      viewFull: 'पूरा मार्गदर्शन देखें →',
      match: 'मिलान',
    },
    caseDetail: {
      loading: 'मार्गदर्शन लोड हो रहा है…',
      couldNotCopy: 'कॉपी नहीं हो सका। कृपया टेक्स्ट चुनकर मैन्युअली कॉपी करें।',
      stepsTitle: '📋 पालन करने के कदम',
      escalationTitle: '⬆️ आगे बढ़ाने की प्रक्रिया',
      templateTitle: '📝 शिकायत टेम्पलेट',
      copied: '✅ कॉपी हुआ!',
      copy: '📋 कॉपी',
      requiredDocs: '📄 आवश्यक दस्तावेज़',
      whomToApproach: '🏛️ किससे संपर्क करें',
      level: 'स्तर',
      portals: '🌐 ऑनलाइन पोर्टल',
      helplines: '📞 हेल्पलाइन नंबर',
      legalHelp: '🆓 मुफ्त कानूनी मदद चाहिए?',
      legalHelpBody: 'जिला विधिक सेवा प्राधिकरण (DLSA) पात्र नागरिकों को मुफ्त कानूनी सहायता देता है।',
      callFree: '📞 15100 पर कॉल करें (मुफ़्त)',
      disclaimer: '⚠️ अस्वीकरण: यह केवल प्रक्रिया मार्गदर्शन है, कानूनी सलाह नहीं। अपनी स्थिति के लिए योग्य वकील से सलाह लें।',
    },
    signin: {
      title: '🔐 साइन इन',
      subtitle: 'NyaySaathi में लॉग इन करें।',
      email: 'ईमेल',
      password: 'पासवर्ड',
      button: 'साइन इन',
      demoNote: 'यह डेमो साइन-इन है (वास्तविक ऑथेंटिकेशन नहीं)।',
      success: '✅ साइन इन सफल (डेमो)।',
    },
    feedback: {
      searching: 'मार्गदर्शन खोजा जा रहा है…',
      searchingSub: '201 कानूनी वर्कफ़्लो में खोज जारी है',
      wentWrong: 'कुछ गलत हो गया',
      unexpected: 'अनपेक्षित त्रुटि हुई। कृपया फिर प्रयास करें।',
      noMatching: 'मिलते-जुलते केस नहीं मिले',
      noMatchingMsgA: 'हमें इस क्वेरी के लिए मैच नहीं मिला:',
      noMatchingMsgB: 'कृपया अपनी समस्या अलग शब्दों में लिखें।',
      tips: 'सुझाव:',
      tip1: 'सरल शब्द प्रयोग करें (जैसे "मकान मालिक जमा वापस नहीं कर रहा")',
      tip2: 'समस्या का प्रकार बताएं (जमीन, वेतन, साइबर फ्रॉड…)',
      tip3: 'मैन्युअली देखने के लिए Browse Categories पेज आज़माएं',
    },
    footer: {
      legalDisclaimer: 'कानूनी अस्वीकरण:',
      legalBody: 'NyaySaathi केवल प्रक्रिया संबंधी मार्गदर्शन देता है और कानूनी सलाह नहीं है। कानूनी सलाह के लिए योग्य वकील से संपर्क करें। मुफ्त कानूनी सहायता आपके नजदीकी जिला विधिक सेवा प्राधिकरण (DLSA) में उपलब्ध है — कॉल करें',
      tagline: 'सामान्य नागरिकों को कानूनी प्रक्रिया ज्ञान से सशक्त बनाना। मुफ़्त। सरल। सुलभ।',
      navigate: 'नेविगेट करें',
      browseCategories: 'श्रेणियां देखें',
      emergency: 'आपातकालीन हेल्पलाइन',
      builtFor: 'भारत के लोगों के लिए बनाया गया।',
      workflowsAndCats: '201 कानूनी वर्कफ़्लो · 10 श्रेणियां',
    },
  },
  mr: {
    common: {
      home: 'मुख्यपृष्ठ',
      categories: 'वर्ग',
      loading: 'लोड होत आहे…',
      tryAgain: 'पुन्हा प्रयत्न करा',
    },
    nav: {
      home: 'मुख्यपृष्ठ',
      find: 'मार्गदर्शन शोधा',
      browse: 'ब्राउज',
      signin: 'साइन इन',
      getHelp: 'मदत घ्या →',
      getHelpNow: 'आता मदत घ्या',
      language: 'भाषा',
      legalGuidance: 'कायदेशीर प्रक्रिया मार्गदर्शन',
    },
    home: {
      forCitizens: '🇮🇳 प्रत्येक भारतीय नागरिकासाठी',
      title1: 'तुमचे',
      title2: 'कायदेशीर हक्क',
      title3: 'माहित नाहीत? आम्ही मार्गदर्शन करू.',
      subtitle: 'तुमची समस्या सोप्या शब्दांत लिहा. NyaySaathi तुम्हाला कोणती पावले घ्यायची, कोणत्या प्राधिकरणाकडे जायचे आणि कोणती कागदपत्रे हवीत ते सांगतो.',
      noteTitle: '⚠️ महत्त्वाची सूचना',
      noteBody: 'NyaySaathi फक्त प्रक्रिया मार्गदर्शन देते, कायदेशीर सल्ला नाही. कायदेशीर प्रतिनिधित्वासाठी पात्र वकिलाशी संपर्क साधा.',
      legalAid: 'मोफत कायदेशीर मदत: कॉल करा',
      howItWorks: 'NyaySaathi कसे काम करते',
      howSub: 'प्रक्रियात्मक मार्गदर्शनासाठी 3 सोपी पावले',
      browseTitle: 'वर्गानुसार पाहा',
      browseSub: 'भारतीय नागरिकांना भेडसावणाऱ्या सामान्य कायदेशीर समस्यांचे 10 वर्ग',
      ctaTitle: 'आत्ता कायदेशीर समस्या आहे का?',
      ctaSub: 'तत्काळ मोफत प्रक्रिया मार्गदर्शन मिळवा — नोंदणी नको.',
      ctaBtn: 'आता मदत घ्या — मोफत आहे →',
      stats: {
        workflows: 'कायदेशीर वर्कफ्लो',
        categories: 'वर्ग',
        free: 'नेहमी मोफत',
        available: 'उपलब्ध',
      },
      steps: {
        oneTitle: 'तुमची समस्या लिहा',
        oneDesc: 'सोप्या भाषेत लिहा — कायदेशीर तांत्रिक शब्द नकोत.',
        twoTitle: 'आम्ही योग्य जुळवणूक करतो',
        twoDesc: 'AI तुमची समस्या 201 केसांमधील योग्य कायदेशीर वर्कफ्लोशी जुळवते.',
        threeTitle: 'पायऱ्या अनुसरा',
        threeDesc: 'स्टेप-बाय-स्टेप मार्गदर्शन, कागदपत्रे व हेल्पलाइन मिळवा.',
      },
    },
    search: {
      badge: '⚖️ मोफत कायदेशीर प्रक्रिया मार्गदर्शन',
      title: 'तुमची कायदेशीर समस्या लिहा',
      subtitle: 'सोप्या भाषेत लिहा — मराठी, हिंदी, इंग्रजी काहीही. सिस्टम अर्थ समजून योग्य मार्गदर्शन शोधेल.',
      commonTitle: 'लोक वारंवार विचारतात:',
      disclaimer: '⚠️ अस्वीकरण: NyaySaathi फक्त प्रक्रिया मार्गदर्शन देते. हे कायदेशीर सल्ला नाही. मोफत कायदेशीर मदतीसाठी कॉल करा',
    },
    searchBox: {
      placeholder: 'तुमची कायदेशीर समस्या तुमच्या शब्दांत लिहा…',
      button: 'मार्गदर्शन शोधा →',
      tryAsking: 'असे विचारून पाहा:',
      examples: [
        'माझ्या नियोक्त्याने 2 महिन्यांपासून पगार दिला नाही',
        'UPI पेमेंटमधून माझी फसवणूक झाली',
        'शेजारी माझ्या जमिनीवर अतिक्रमण करतो आहे',
        'घरमालक सिक्युरिटी डिपॉझिट परत देत नाही',
        'ऑनलाइन घेतलेला उत्पादन खराब निघाला',
      ],
    },
    results: {
      analysing: 'तुमच्या समस्येचे विश्लेषण चालू आहे…',
      understoodAs: 'सिस्टमने तुमची क्वेरी अशी समजली:',
      aiEnhanced: '⚡ AI उन्नत',
      high: 'उच्च विश्वास',
      medium: 'मध्यम विश्वास',
      low: 'कमी विश्वास',
      matchesFound: 'जुळणारे मार्गदर्शन वर्कफ्लो सापडले',
      oneMatchFound: 'जुळणारा मार्गदर्शन वर्कफ्लो सापडला',
      noResults: 'निकाल सापडला नाही',
      disclaimer: '⚠️ अस्वीकरण: NyaySaathi फक्त प्रक्रिया मार्गदर्शन देते, कायदेशीर सल्ला नाही. मोफत कायदेशीर मदतीसाठी कॉल करा',
      browseAll: 'सर्व वर्ग पहा →',
    },
    categories: {
      title: '📚 कायदेशीर वर्ग ब्राउज करा',
      subtitle: '✨ 10 समस्या वर्ग आणि 201 कायदेशीर वर्कफ्लो पहा',
      allCategories: '🗂️ सर्व वर्ग',
      workflows: 'वर्कफ्लो',
      selectPromptTitle: '👆 ब्राउज करण्यासाठी वर्ग निवडा',
      selectPromptBody: 'यादीतील कोणताही वर्ग निवडा आणि संबंधित कायदेशीर वर्कफ्लो पहा.',
      searchDirect: '🔎 किंवा तुमची समस्या थेट शोधा →',
      loadingCats: 'वर्ग लोड होत आहेत…',
      loadingCases: 'वर्कफ्लो लोड होत आहेत…',
      viewGuidance: '👉 मार्गदर्शन पहा →',
    },
    caseCard: {
      stepsToFollow: 'अनुसरण्याच्या पायऱ्या',
      moreSteps: 'अजून पायऱ्या',
      documentsNeeded: 'कागदपत्रे आवश्यक',
      viewFull: 'पूर्ण मार्गदर्शन पहा →',
      match: 'जुळणी',
    },
    caseDetail: {
      loading: 'मार्गदर्शन लोड होत आहे…',
      couldNotCopy: 'कॉपी करता आले नाही. कृपया मजकूर निवडून स्वतः कॉपी करा.',
      stepsTitle: '📋 अनुसरण्याच्या पायऱ्या',
      escalationTitle: '⬆️ पुढील पातळी प्रक्रिया',
      templateTitle: '📝 तक्रार नमुना',
      copied: '✅ कॉपी झाले!',
      copy: '📋 कॉपी',
      requiredDocs: '📄 आवश्यक कागदपत्रे',
      whomToApproach: '🏛️ कुणाकडे जावे',
      level: 'पातळी',
      portals: '🌐 ऑनलाइन पोर्टल',
      helplines: '📞 हेल्पलाइन क्रमांक',
      legalHelp: '🆓 मोफत कायदेशीर मदत हवी?',
      legalHelpBody: 'जिल्हा विधी सेवा प्राधिकरण (DLSA) पात्र नागरिकांना मोफत कायदेशीर मदत देते.',
      callFree: '📞 15100 वर कॉल करा (मोफत)',
      disclaimer: '⚠️ अस्वीकरण: हे फक्त प्रक्रिया मार्गदर्शन आहे, कायदेशीर सल्ला नाही. तुमच्या परिस्थितीसाठी पात्र वकिलाचा सल्ला घ्या.',
    },
    signin: {
      title: '🔐 साइन इन',
      subtitle: 'NyaySaathi खात्यात लॉगिन करा.',
      email: 'ईमेल',
      password: 'पासवर्ड',
      button: 'साइन इन',
      demoNote: 'हे डेमो साइन-इन आहे (खरे authentication नाही).',
      success: '✅ यशस्वी साइन इन (डेमो).',
    },
    feedback: {
      searching: 'मार्गदर्शन शोधले जात आहे…',
      searchingSub: '201 कायदेशीर वर्कफ्लोमध्ये शोध चालू आहे',
      wentWrong: 'काहीतरी चूक झाली',
      unexpected: 'अनपेक्षित त्रुटी झाली. कृपया पुन्हा प्रयत्न करा.',
      noMatching: 'जुळणारे केस सापडले नाहीत',
      noMatchingMsgA: 'या क्वेरीसाठी जुळणी सापडली नाही:',
      noMatchingMsgB: 'कृपया समस्या वेगळ्या शब्दांत लिहा.',
      tips: 'सूचना:',
      tip1: 'सोपे शब्द वापरा (उदा. "घरमालक डिपॉझिट परत देत नाही")',
      tip2: 'समस्येचा प्रकार नमूद करा (जमीन, पगार, सायबर फसवणूक…)',
      tip3: 'हाताने शोधण्यासाठी Browse Categories पेज वापरा',
    },
    footer: {
      legalDisclaimer: 'कायदेशीर अस्वीकरण:',
      legalBody: 'NyaySaathi फक्त प्रक्रिया मार्गदर्शन देते आणि कायदेशीर सल्ला नाही. कायदेशीर सल्ल्यासाठी पात्र वकिलाशी संपर्क करा. मोफत कायदेशीर मदत तुमच्या जवळच्या जिल्हा विधी सेवा प्राधिकरण (DLSA) येथे उपलब्ध आहे — कॉल करा',
      tagline: 'सामान्य नागरिकांना कायदेशीर प्रक्रियेचे ज्ञान देऊन सक्षम करणे. मोफत. सोपे. सर्वांसाठी.',
      navigate: 'नेव्हिगेट',
      browseCategories: 'वर्ग ब्राउज करा',
      emergency: 'आपत्कालीन हेल्पलाइन',
      builtFor: 'भारतातील लोकांसाठी तयार केले.',
      workflowsAndCats: '201 कायदेशीर वर्कफ्लो · 10 वर्ग',
    },
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang] = useState('en')

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, 'en')
  }, [])

  const value = useMemo(() => {
    const strings = STRINGS[lang] || STRINGS.en

    const t = (path) => {
      const parts = String(path).split('.')
      let cur = strings
      for (const p of parts) cur = cur?.[p]
      return cur ?? path
    }

    const setLang = () => {}
    const toggleLang = () => {}

    return { lang, setLang, toggleLang, t }
  }, [lang])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within <LanguageProvider>')
  return ctx
}
