"""Central runtime configuration for NyaySaathi backend reliability layers."""

from __future__ import annotations

import os

from dotenv import load_dotenv

load_dotenv()

SUPPORTED_LANGUAGES = ["en", "hi", "mr"]
DEFAULT_LANGUAGE = os.getenv("DEFAULT_LANGUAGE", "en")
LANG_DETECT_MIN_CONFIDENCE = float(os.getenv("LANG_DETECT_MIN_CONFIDENCE", "0.70"))

TRANSLATION_TIMEOUT = float(os.getenv("TRANSLATION_TIMEOUT", "10"))
TRANSLATION_RETRIES = int(os.getenv("TRANSLATION_RETRIES", "2"))
TRANSLATION_CB_THRESHOLD = int(os.getenv("TRANSLATION_CB_THRESHOLD", "4"))
TRANSLATION_CB_COOLDOWN = float(os.getenv("TRANSLATION_CB_COOLDOWN", "45"))

ROMAN_NORMALIZER_TIMEOUT = float(os.getenv("ROMAN_NORMALIZER_TIMEOUT", "8"))
ROMAN_NORMALIZER_RETRIES = int(os.getenv("ROMAN_NORMALIZER_RETRIES", "1"))

EMBEDDING_MODEL = os.getenv("EMBEDDING_MODEL", "sentence-transformers/all-MiniLM-L6-v2")
SEMANTIC_MATCH_THRESHOLD = float(os.getenv("SEMANTIC_MATCH_THRESHOLD", "0.55"))
FALLBACK_SIMILARITY_THRESHOLD = float(os.getenv("FALLBACK_SIMILARITY_THRESHOLD", "0.50"))
HIGH_CONFIDENCE_THRESHOLD = float(os.getenv("HIGH_CONFIDENCE_THRESHOLD", "0.75"))
MEDIUM_CONFIDENCE_THRESHOLD = float(os.getenv("MEDIUM_CONFIDENCE_THRESHOLD", "0.55"))
EMBEDDING_CACHE_TTL_SECONDS = int(os.getenv("EMBEDDING_CACHE_TTL_SECONDS", "900"))
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "64"))
UNDERSTANDING_CACHE_TTL_SECONDS = int(os.getenv("UNDERSTANDING_CACHE_TTL_SECONDS", "300"))
